#!/usr/bin/env python3
"""
daily-notes.py — generates a dated daily note in ~/.hermes/notes/
Pattern from r/hermesagent community: searchable timeline of decisions/actions.

Schedule: daily 7:00am (before morning briefing)
Output: ~/.hermes/notes/YYYY-MM-DD.md
"""
import os
import datetime
import json

NOTES_DIR = os.path.expanduser("~/.hermes/notes")
PROFILE_DIR = os.path.expanduser("~/.hermes/profiles")
ACTIVITY_DIR = os.path.expanduser("~/.hermes/activity")
SESSION_DB = os.path.expanduser("~/.hermes/sessions/session.db")


def get_today():
    return datetime.date.today().isoformat()


def get_yesterday_sessions():
    """Pull yesterday's session count + last 5 lines from activity log if present."""
    yesterday = (datetime.date.today() - datetime.timedelta(days=1)).isoformat()
    activity_file = os.path.join(ACTIVITY_DIR, f"{yesterday}.md")
    last_lines = []
    if os.path.exists(activity_file):
        with open(activity_file) as f:
            last_lines = f.readlines()[-5:]
    return last_lines


def get_pending_cron_jobs():
    """List any cron jobs that errored in the last 24h."""
    jobs_file = os.path.expanduser("~/.hermes/cron/jobs.json")
    if not os.path.exists(jobs_file):
        return []
    with open(jobs_file) as f:
        data = json.load(f)
    err_jobs = [j for j in data.get("jobs", []) if j.get("last_status") == "error"]
    return [{"name": j.get("name"), "id": j.get("id")[:8]} for j in err_jobs[:5]]


def get_active_profiles():
    return [d for d in os.listdir(PROFILE_DIR) if os.path.isdir(os.path.join(PROFILE_DIR, d))]


def write_daily_note():
    today = get_today()
    note_path = os.path.join(NOTES_DIR, f"{today}.md")
    os.makedirs(NOTES_DIR, exist_ok=True)

    yesterday_lines = get_yesterday_sessions()
    cron_errors = get_pending_cron_jobs()
    profiles = get_active_profiles()

    content = f"""# 📅 {today} — Daily Note

> Generated by `daily-notes.py` (cron job). Edit freely — this is your searchable timeline.

## 🎯 Today's Focus

<!-- Add your top 3 priorities here -->

1. 
2. 
3. 

## 📊 System Status

- **Profiles active:** {len(profiles)} ({', '.join(profiles)})
- **Cron errors (24h):** {len(cron_errors)}
{chr(10).join(f"  - {e['name']} ({e['id']})" for e in cron_errors) if cron_errors else "  - (none)"}

## 📝 Yesterday's Activity (last 5 lines)

```
{chr(10).join(yesterday_lines) if yesterday_lines else '(no activity log found)'}
```

## 🛠️ Decisions & Actions

<!-- Log decisions as you make them — these become the searchable timeline -->
<!-- Format: HH:MM | [profile] | [action] | [result] -->

- 

## 💡 Notes & Ideas

- 

## 📎 Links & References

- 

---

*Auto-regenerated daily at 07:00. Hermes uses this for context.*
"""
    with open(note_path, "w") as f:
        f.write(content)
    return note_path


if __name__ == "__main__":
    path = write_daily_note()
    print(f"✅ Daily note written: {path}")
