#!/usr/bin/env python3
"""
register_client — single command to onboard a new client repo.

Creates:
  1. Kanban board (e.g. <client>-tasks or uses existing)
  2. AGENTS.md in the repo (bot-ready template)
  3. designer-handoff.json stub (if doesn't exist)
  4. Registers in repo_context.json (single source of truth)
  5. Sets up tenant if not exists

Usage:
  register_client.py --repo /path/to/repo --tenant "client-co" \
    --human-owner "Kiki" --agent-owner "design-bot" \
    --deploy-status staging --live-url "https://client.example.com"

Idempotent: re-runnable, won't overwrite existing files.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from kanban_common import INBOX_DIR, eprint, today_iso
import subprocess
import repo_context as rc


def ensure_kanban_board(board_name: str, force: bool = False) -> bool:
    """Create kanban board, return True if created."""
    db = Path("/root/.hermes/kanban/boards") / board_name / "kanban.db"
    if db.exists() and not force:
        print(f"  ⏭ board exists: {board_name}")
        return False
    r = subprocess.run(
        ["hermes", "kanban", "boards", "create", board_name],
        capture_output=True, text=True,
    )
    if r.returncode == 0:
        print(f"  ✓ created kanban board: {board_name}")
        return True
    else:
        # board may already exist in some state, just skip
        print(f"  ! could not create board: {r.stderr[:200]}")
        return False


def write_agents_md(repo_path: Path, client_name: str, tenant: str,
                     human_owner: str, agent_owner: str, live_url: str) -> None:
    """Write AGENTS.md if missing."""
    agents_md = repo_path / "AGENTS.md"
    if agents_md.exists():
        print(f"  ⏭ AGENTS.md exists in {repo_path.name}")
        return
    content = f"""# AGENTS.md — {client_name} ({repo_path.name})

> Bot-ready operational playbook for this repo.
> Auto-generated by `register_client.py` on {today_iso()}.

## Tenant & Ownership

- **Tenant**: `{tenant}`
- **Human owner**: {human_owner}
- **Bot owner**: `{agent_owner}`
- **Live URL**: {live_url or "(not set)"}

## Bot Workflow

When a bot picks up a kanban task for this repo:

1. Read this AGENTS.md first
2. `python3 ~/.hermes/scripts/repo_context.py lookup {client_name}` for cross-reference
3. Read `designer-handoff.json` for brand (if exists)
4. Run `python3 ~/.hermes/scripts/kanban_bot_inspect.py {agent_owner}` for current state
5. Run relevant tests / build / lint before marking done
6. Update kanban task with summary

## Brand System

- **Designer**: Lua (Luana López)
- **Design executor**: design-bot
- **Brand file**: `designer-handoff.json` (if missing, run `designer_handoff_validate.py`)
- **WCAG**: AA minimum, AAA preferred

## Deploy

- Build: check `package.json` scripts
- Deploy: see `~/.hermes/profiles/delivery-bot/AGENTS.md`
- Health: `bash ~/.hermes/scripts/site-healthcheck.sh {live_url or 'https://localhost:3000'}`

## Kanban Board

- Tasks: see `hermes kanban --board <board>` (default: `client-deploy`)

## Cross-references

- `~/.hermes/profiles/{agent_owner}/SOUL.md` — bot identity
- `~/.hermes/profiles/{agent_owner}/AGENTS.md` — bot playbook
- `~/.hermes/scripts/repo_context.py` — single source of truth
- `~/.hermes/inbox/repo_context.json` — registry state

---

*Edit this file to add repo-specific conventions. The bot will read it.*
"""
    agents_md.write_text(content)
    print(f"  ✓ wrote AGENTS.md: {agents_md}")


def write_designer_handoff(repo_path: Path, client_name: str) -> None:
    """Write designer-handoff.json stub if missing."""
    handoff = repo_path / "designer-handoff.json"
    if handoff.exists():
        print(f"  ⏭ designer-handoff.json exists in {repo_path.name}")
        return
    content = {
        "client": client_name,
        "version": "0.1.0",
        "created": today_iso(),
        "_note": "Stub - run designer_handoff_validate.py to fill in",
        "palette": {
            "primary": "TBD",
            "secondary": "TBD",
            "neutral": "TBD",
            "semantic": {"success": "TBD", "warning": "TBD", "danger": "TBD"}
        },
        "typography": {
            "heading": "TBD",
            "body": "TBD"
        },
        "constraints": {
            "wcag": "AA"
        }
    }
    handoff.write_text(json.dumps(content, indent=2))
    print(f"  ✓ wrote designer-handoff.json: {handoff}")


def main():
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--repo", required=True, help="absolute path to client repo")
    p.add_argument("--tenant", required=True, help="tenant name (client or internal)")
    p.add_argument("--client-name", help="short client name (defaults to repo dir name)")
    p.add_argument("--human-owner", default="Ivan", help="which human owns it")
    p.add_argument("--agent-owner", default="design-bot", help="which bot owns it")
    p.add_argument("--deploy-status", choices=["draft", "staging", "live", "broken"], default="staging")
    p.add_argument("--live-url", help="live URL")
    p.add_argument("--board", default="client-deploy", help="kanban board")
    p.add_argument("--tags", nargs="*", default=[], help="tags (nextjs, tailwind-v4, etc.)")
    args = p.parse_args()

    repo_path = Path(args.repo).resolve()
    if not repo_path.exists():
        eprint(f"repo does not exist: {repo_path}")
        sys.exit(1)
    if not repo_path.is_dir():
        eprint(f"not a directory: {repo_path}")
        sys.exit(1)

    client_name = args.client_name or repo_path.name
    print(f"\n{'='*70}\nregister_client: {client_name}\n{'='*70}")
    print(f"  repo:   {repo_path}")
    print(f"  tenant: {args.tenant}")
    print(f"  bot:    {args.agent_owner}")
    print(f"  human:  {args.human_owner}")

    # 1. Ensure tenant exists in repo_context
    ctx = rc.load()
    if args.tenant not in ctx.get("tenants", {}):
        result = subprocess.run(
            ["python3", str(Path(__file__).parent / "repo_context.py"),
             "register-tenant", args.tenant,
             "--description", f"Auto-registered from {repo_path.name}",
             "--contact", args.human_owner],
            capture_output=True, text=True,
        )
        if result.returncode != 0:
            eprint(f"failed to register tenant: {result.stderr}")

    # 2. Ensure board exists
    print("\n[1] Kanban board:")
    ensure_kanban_board(args.board)

    # 3. Write AGENTS.md
    print("\n[2] AGENTS.md:")
    write_agents_md(repo_path, client_name, args.tenant,
                    args.human_owner, args.agent_owner, args.live_url)

    # 4. Write designer-handoff.json
    print("\n[3] designer-handoff.json:")
    write_designer_handoff(repo_path, client_name)

    # 5. Register in repo_context
    print("\n[4] repo_context.py:")
    cmd = [
        "python3", str(Path(__file__).parent / "repo_context.py"),
        "register-repo", str(repo_path), args.tenant,
        "--agent-owner", args.agent_owner,
        "--human-owner", args.human_owner,
        "--deploy-status", args.deploy_status,
        "--live-url", args.live_url or "",
        "--kanban-board", args.board,
    ]
    if args.tags:
        cmd += ["--tags"] + args.tags
    subprocess.run(cmd, check=True)

    print(f"\n{'='*70}\n✓ Done. {client_name} is now bot-ready.\n")
    print(f"Test with: python3 ~/.hermes/scripts/repo_context.py lookup {client_name}")
    print(f"Or:        python3 ~/.hermes/scripts/kanban_bot_inspect.py {args.agent_owner}")


if __name__ == "__main__":
    main()
